### ISSUE TITLE
Upload File Error

### ISSUE THREAD

**Issue by ChinmayX** [yinkakun/medusa-file-supabase#1]
![image](https://github.com/yinkakun/medusa-file-supabase/assets/73830844/30471c13-c89e-4e66-9e7c-1a01b00c0fa0)
![image](https://github.com/yinkakun/medusa-file-supabase/assets/73830844/0d987140-6bfe-45f2-ab14-1f46249ac971)

came across this issue with node
https://github.com/nodejs/node/issues/46221

**Comment by Sid110307** [comment]
Hey
I've sent a PR to the repo fixing this.
